apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: khoj-secret
  namespace: khoj
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: khoj-secret
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: khoj
      property: postgres_password
  - secretKey: DJANGO_SECRET_KEY
    remoteRef:
      key: khoj
      property: django_secret_key
  - secretKey: ADMIN_PASSWORD
    remoteRef:
      key: khoj
      property: admin_password
