apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-webui
  namespace: ollama-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-webui
  template:
    metadata:
      labels:
        app: ollama-webui
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: ollama-webui
          image: ghcr.io/open-webui/open-webui:git-c5b5303-cuda
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              memory: 8000Mi
          envFrom:
            - configMapRef:
                name: ollama-webui-configmap
          volumeMounts:
            - name: data
              mountPath: /app/backend/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ollama-webui-storage-pvc
