# PV definition removed
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nestmtx-storage-pvc
  namespace: nestmtx
  labels:
    app: nestmtx
    type: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

