apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: searxng
  labels:
    app: searxng
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
