apiVersion: v1
kind: ConfigMap
metadata:
  name: hoarder-configuration
  namespace: hoarder
data:
  # Add any non-secret configuration values here
  NEXTAUTH_URL: "https://hoarder.vanillax.me"
  OLLAMA_BASE_URL: "https://ollama.vanillax.me/api"
  OLLAMA_KEEP_ALIVE: "5m"
  INFERENCE_TEXT_MODEL: "llama3.2"
  INFERENCE_IMAGE_MODEL: "llava"
  EMBEDDING_TEXT_MODEL: "granite-embedding:278m"
  # For webhook functionality (new in 0.22.0)
  WEBHOOK_ENABLED: "false"
  # Add any other configuration values as needed 
