apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoarder-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoarder-web
  template:
    metadata:
      labels:
        app: hoarder-web
    spec:
      containers:
        - name: web
          image: ghcr.io/karakeep-app/karakeep:0.25.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MEILI_ADDR
              value: http://hoarder-meilisearch.hoarder.svc.cluster.local:7700
            - name: BROWSER_WEB_URL
              value: http://hoarder-chrome.hoarder.svc.cluster.local:9222
            - name: DATA_DIR
              value: /data
              # Add OPENAI_API_KEY to the ConfigMap if necessary
          volumeMounts:
            - mountPath: /data
              name: data
          envFrom:
            - secretRef:
                name: hoarder-secret
            - configMapRef:
                name: hoarder-configuration
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
