apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hoarder-secrets
  namespace: hoarder
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: hoarder-secret
    creationPolicy: Owner
  data:
  - secretKey: OPENAI_KEY
    remoteRef:
      key: hoarder-secret
      property: hoarder-openai
  - secretKey: NEXTAUTH_SECRET
    remoteRef:
      key: hoarder-secret
      property: hoarder-nextauth
  - secretKey: MEILI_SECRET
    remoteRef:
      key: hoarder-secret
      property: hoarder-meili
  - secretKey: WEBHOOK_SECRET
    remoteRef:
      key: hoarder-secret
      property: hoarder-webhook
  - secretKey: NEXTAUTH_PUBLIC_SECRET
    remoteRef:
      key: hoarder-secret
      property: hoarder-nextauth-public_secret
