apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: control-plane-vip-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.8.51"
      stop: "192.168.8.60"
  serviceSelector:
    matchLabels:
      app: kube-apiserver-vip
