apiVersion: v1
kind: PersistentVolume
metadata:
  name: single-example-data-pv
  labels:
    app: cloudnative-pg
    cluster: single-example
    type: data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /datapool/kubernetes/postgres/single-example/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vanillax-ai
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: single-example-wal-pv
  labels:
    app: cloudnative-pg
    cluster: single-example
    type: wal
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /datapool/kubernetes/postgres/single-example/wal
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vanillax-ai

######IMMICH#####
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-database-1-data-pv
  labels:
    app: cloudnative-pg
    cluster: immich-database
    instance: "1"
    type: data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /datapool/kubernetes/postgres/immich-database/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vanillax-ai
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-database-1-wal-pv
  labels:
    app: cloudnative-pg
    cluster: immich-database
    instance: "1"
    type: wal
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /datapool/kubernetes/postgres/immich-database/wal
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vanillax-ai
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-database-2-data-pv
  labels:
    app: cloudnative-pg
    cluster: immich-database
    instance: "2"
    type: data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /datapool/kubernetes/postgres/immich-database-2/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vanillax-ai
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-database-2-wal-pv
  labels:
    app: cloudnative-pg
    cluster: immich-database
    instance: "2"
    type: wal
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /datapool/kubernetes/postgres/immich-database-2/wal
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vanillax-ai
