apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
commonLabels:
  app.kubernetes.io/name: immich
  app.kubernetes.io/component: machine-learning
  app.kubernetes.io/managed-by: argocd
resources:
  - deployment.yaml
  - service.yaml 