apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  selector:
    app: immich
    component: machine-learning
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
