apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  capacity:
    storage: 1Gi  # Minimal size since it's just for mounting
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - cache=strict
    - nosharesock
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: jellyfin-media-volume
    volumeAttributes:
      source: "//192.168.10.133/jellyfin-media"
    nodeStageSecretRef:
      name: smbcreds
      namespace: csi-driver-smb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Minimal size since it's just for mounting
  volumeName: jellyfin-media
  storageClassName: ""