apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: jellyfin

configMapGenerator:
  - name: jellyfin-env
    namespace: jellyfin
    literals:
      - TZ="America/Detroit"

resources:
  - ns.yaml
  # - svc.yaml
  # - pvc.yaml
  # - jellyfin-media-pvc.yaml
  # - deployment.yaml
  # - httproute.yaml
