apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
commonLabels:
  app.kubernetes.io/name: kafka
  app.kubernetes.io/managed-by: argocd
resources:
  - kafka-cluster.yaml
  - topics.yaml
