apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frigate
spec:
  parentRefs:
    - name: gateway-internal
      namespace: gateway
  hostnames:
  - "frigate.vanillax.me"
  rules:
  - matches:
    - path:
        type: PathPrefix 
        value: /
    backendRefs:
        - name: frigate-http
          port: 5000
