apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxitok-cache-pvc
  namespace: proxitok
  labels:
    app: proxitok
    type: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---

