apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: comfyui-route
  namespace: comfyui
spec:
  parentRefs:
    - name: gateway-internal
      namespace: gateway
  hostnames:
    - comfyui.vanillax.me
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: comfyui-service
          port: 8188
