apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-storage
  namespace: comfyui
  annotations:
    volume.longhorn.io/numberOfReplicas: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 180Gi
  storageClassName: longhorn
